spring.application.name=This-is-the-simple-project.

spring.application.name=This-is-the-simple-project

server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://db.tzikhmxwthwkghycyzec.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=Abhishek805623@@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
